/** Stitch "Obsidian Trade" 设计 token —— 直接搬自 DESIGN.md frontmatter。 */
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#10131c",
        "surface-dim": "#10131c",
        "surface-bright": "#363943",
        "surface-container-lowest": "#0b0e17",
        "surface-container-low": "#181b25",
        "surface-container": "#1c1f29",
        "surface-container-high": "#272a34",
        "surface-container-highest": "#31343f",
        "on-surface": "#e0e2ef",
        "on-surface-variant": "#c7c4d7",
        "inverse-surface": "#e0e2ef",
        "inverse-on-surface": "#2d303a",
        outline: "#908fa0",
        "outline-variant": "#464554",
        "surface-tint": "#c0c1ff",
        primary: "#c0c1ff",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "on-primary-container": "#0d0096",
        "inverse-primary": "#494bd6",
        secondary: "#7bd0ff",
        "on-secondary": "#00354a",
        "secondary-container": "#00a6e0",
        tertiary: "#ddb7ff",
        "on-tertiary": "#490080",
        "tertiary-container": "#b76dff",
        error: "#ffb4ab",
        "error-container": "#93000a",
        background: "#10131c",
        "on-background": "#e0e2ef",
        "surface-variant": "#31343f",
        bullish: "#10B981",
        bearish: "#EF4444",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["44px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-base": ["15px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-bold": ["15px", { lineHeight: "1.5", fontWeight: "600" }],
        "data-mono": ["13px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
    },
  },
  plugins: [],
};
